# Generated by Django 6.0.1 on 2026-01-15 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tipo', models.CharField(choices=[('OCASIONAL', 'Ocasional'), ('SEMANAL', 'Semestral')], max_length=10)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.aula')),
                ('catedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracion.catedra')),
                ('requerimientos', models.ManyToManyField(to='configuracion.requerimiento')),
            ],
        ),
    ]
