# Generated by Django 6.0.1 on 2026-01-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_inicio',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_fin',
            new_name='fecha_fin_semestre',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('ocasional', 'Ocasional'), ('semestral', 'Semestral')], max_length=10),
        ),
    ]
