# Generated by Django 5.2.10 on 2026-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_fecha_inicio_reserva_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
